name: step 1 and notify to above

on:
  workflow_dispatch:
    inputs:
      downstream-repository:
        description: "Target repository owner/name to notify"
        type: string
        default: "keshavsoft/vs-code-ext-from-any-js"
        required: true
      event-type:
        description: "Repository dispatch event type to send"
        type: string
        default: "dependency-updated"
        required: true
      workflow-name:
        description: "Filename of the workflow in the target repository to monitor"
        type: string
        default: "update-dependency.yml"
        required: true
      node-version:
        description: "Node.js version to use"
        type: string
        default: "20"
        required: false

jobs:
  publish:
    name: NPM Publish Task
    uses: ./.github/workflows/npm-publish.yml
    with:
      node-version: ${{ inputs.node-version }}
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  notify:
    name: Dispatch Notification Task
    needs: publish
    if: needs.publish.outputs.status == 'published'
    uses: ./.github/workflows/notify-repo.yml
    with:
      repository: ${{ inputs.downstream-repository }}
      event-type: ${{ inputs.event-type }}
      client-payload: '{"package": "${{ needs.publish.outputs.package_name }}"}'
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}

  wait:
    name: Wait for Build Task
    needs: [publish, notify]
    if: needs.publish.outputs.status == 'published'
    uses: ./.github/workflows/wait-for-workflow.yml
    with:
      repository: ${{ inputs.downstream-repository }}
      workflow-name: ${{ inputs.workflow-name }}
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
